services:

  _defaults:
      autowire: true
      autoconfigure: true

  Rehark\ApiGeneratorBundle\:
    resource: '../src/*'
    exclude:
      - '../src/DependencyInjection/'

  RehArk\ApiGeneratorBundle\Command\:
    resource: '../src/Command'
    tags: ['console.command']